services:
  hioshop-server:
    image: beisitech/hioshop-server:latest
    container_name: hioshop-server
    environment:
      NODE_ENV: production
      PORT: 8360
    expose:
      - "8360"
    volumes:
      - ./runtime:/srv/hioshop/runtime
    restart: unless-stopped
    networks:
      - beisi-network

  hioshop-admin:
    image: beisitech/hioshop-admin:latest
    container_name: hioshop-admin
    restart: on-failure:3
      - .env
    networks:
      - beisi-network

networks:
  beisi-network:
    external: true
    name: beisi-shared-network
